language: php
sudo: false
matrix:
  include:
  - php: '5.3'
    dist: precise
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
  - php: nightly
before_script:
 - phpenv rehash
 - export PATH=$PATH:`composer config bin-dir --absolute`
install:
 - composer self-update
 - composer require squizlabs/php_codesniffer
 - composer install
script:
 - make sniff || echo "Completed - Returned $?"
 - make test
